# Generated by Django 5.2.6 on 2026-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freshArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('freshtitle', models.CharField(max_length=100)),
                ('freshMrp', models.IntegerField()),
                ('freshprice', models.IntegerField()),
                ('freshoffer', models.IntegerField()),
            ],
        ),
    ]
