# Generated by Django 5.2.6 on 2026-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresharrivals', '0002_alter_fresharrivals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fresharrivals',
            options={'verbose_name_plural': 'Fresh Arrivals'},
        ),
        migrations.AlterField(
            model_name='fresharrivals',
            name='freshImage',
            field=models.ImageField(blank=True, null=True, upload_to='fresh_arrivals/'),
        ),
    ]
