# Generated by Django 6.0.2 on 2026-03-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Mrp', models.IntegerField()),
                ('Offer', models.IntegerField()),
                ('Bestprice', models.IntegerField()),
            ],
        ),
    ]
