# Generated by Django 5.2.6 on 2026-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwearImage', models.ImageField(upload_to='')),
                ('footwearName', models.CharField(max_length=100)),
                ('footwearPrice', models.IntegerField()),
                ('footwearMrp', models.IntegerField()),
                ('footwearOffer', models.IntegerField()),
                ('footwearBestprice', models.IntegerField()),
            ],
        ),
    ]
