# Generated by Django 6.0.2 on 2026-02-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirtImage', models.ImageField(upload_to='')),
                ('tshirtName', models.CharField(max_length=100)),
                ('tshirtPrice', models.IntegerField()),
                ('tshirtMrp', models.IntegerField()),
                ('tshirtOffer', models.IntegerField()),
                ('tshirtBestprice', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'TopWear',
            },
        ),
    ]
