# Generated by Django 6.0.2 on 2026-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winterwearitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winterwearImage', models.ImageField(upload_to='')),
                ('winterwearName', models.CharField(max_length=100)),
                ('winterwearPrice', models.IntegerField()),
                ('winterwearMrp', models.IntegerField()),
                ('winterwearOffer', models.IntegerField()),
                ('winterwearBestprice', models.IntegerField()),
            ],
        ),
    ]
