# Generated by Django 5.2.6 on 2026-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Winterwearapp', '0002_alter_winterwearitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winterwearitems',
            name='winterwearImage',
            field=models.ImageField(upload_to='winterwear/'),
        ),
    ]
