# Generated by Django 6.0.2 on 2026-02-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Winterwearapp', '0003_alter_winterwearitems_winterwearimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winterwearitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
