# Generated by Django 5.2.6 on 2026-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenimItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denimImage', models.ImageField(upload_to='')),
                ('denimName', models.CharField(max_length=100)),
                ('denimPrice', models.IntegerField()),
                ('denimMrp', models.IntegerField()),
                ('denimOffer', models.IntegerField()),
                ('denimBestprice', models.IntegerField()),
            ],
        ),
    ]
