# Generated by Django 6.0.2 on 2026-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poloitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poloImage', models.ImageField(upload_to='')),
                ('poloName', models.CharField(max_length=100)),
                ('poloPrice', models.IntegerField()),
                ('poloMrp', models.IntegerField()),
                ('poloOffer', models.IntegerField()),
                ('poloBestprice', models.IntegerField()),
            ],
        ),
    ]
